version: '3.8'
services:
  backend:
    build: 
      dockerfile: Dockerfile
    container_name: calibration-system-be
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - ENV=${ENV}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GOOGLE_OAUTH_REDIRECT_URL=${GOOGLE_OAUTH_REDIRECT_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SENDER=${SMTP_SENDER}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASS=${SMTP_PASS}
      - WA_API_URL=${WA_API_URL}
      - WA_TEMPLATE_ID=${WA_TEMPLATE_ID}
      - WA_API_KEY=${WA_API_KEY}
      - WA_SHORTEN_URL=${WA_SHORTEN_URL}
    ports:
      - ${API_PORT}:5000
    depends_on:
      - db
      - redis
    networks:
      - calibration-system-network
  db:
    image: postgres:alpine3.17
    container_name: calibration-system-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - calibration-system-network
  redis:
    image: 'bitnami/redis:latest'
    container_name: calibration-system-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis_data/:/bitnami/redis/data/
    networks:
      - calibration-system-network
volumes:
  db-data:
networks:
  calibration-system-network: